CANDIDATES = [
    {
        "id": 1,
        "name": "Priya Sharma",
        "title": "Senior ML Engineer",
        "years_experience": 6,
        "skills": ["Python", "PyTorch", "NLP", "MLOps", "Hugging Face", "FastAPI", "Docker"],
        "domain": "AI/ML",
        "bio": "Built production NLP pipelines at a Series B startup handling 50M+ requests/day. Expert in LLM fine-tuning, RLHF, and end-to-end model deployment.",
        "availability": "immediate",
        "location": "Bangalore, India",
        "education": "M.Tech, IIT Bombay",
        "avatar": "PS",
        "linkedin": "linkedin.com/in/priya-sharma-ml",
    },
    {
        "id": 2,
        "name": "Alex Chen",
        "title": "ML Platform Lead",
        "years_experience": 8,
        "skills": ["Python", "TensorFlow", "NLP", "Kubernetes", "Docker", "Spark", "MLflow"],
        "domain": "AI/ML",
        "bio": "Led ML platform team at a unicorn company scaling to 200+ models in production. Deep expertise in scalable model serving and A/B testing infrastructure.",
        "availability": "1 month",
        "location": "San Francisco, USA",
        "education": "MS Computer Science, Stanford",
        "avatar": "AC",
        "linkedin": "linkedin.com/in/alex-chen-ml",
    },
    {
        "id": 3,
        "name": "Rahul Verma",
        "title": "NLP Engineer",
        "years_experience": 4,
        "skills": ["Python", "PyTorch", "NLP", "BERT", "Transformers", "spaCy", "FastAPI"],
        "domain": "NLP",
        "bio": "Specialized in transformer architectures and multilingual NLP systems. Built entity extraction and document classification systems used by 10+ enterprise clients.",
        "availability": "immediate",
        "location": "Hyderabad, India",
        "education": "B.Tech, NIT Warangal",
        "avatar": "RV",
        "linkedin": "linkedin.com/in/rahul-verma-nlp",
    },
    {
        "id": 4,
        "name": "Sarah Kim",
        "title": "MLOps Engineer",
        "years_experience": 5,
        "skills": ["MLOps", "Kubernetes", "Python", "CI/CD", "Airflow", "Terraform", "Prometheus"],
        "domain": "MLOps",
        "bio": "Built end-to-end ML pipelines from training to monitoring. Expert in model drift detection, retraining automation, and multi-cloud deployment.",
        "availability": "3 months",
        "location": "Seattle, USA",
        "education": "BS Computer Engineering, UW",
        "avatar": "SK",
        "linkedin": "linkedin.com/in/sarah-kim-mlops",
    },
    {
        "id": 5,
        "name": "Mohammed Al-Rashid",
        "title": "AI Research Engineer",
        "years_experience": 7,
        "skills": ["Python", "PyTorch", "NLP", "LLM fine-tuning", "RLHF", "Hugging Face", "CUDA"],
        "domain": "AI Research",
        "bio": "PhD in NLP from CMU with publications on instruction tuning and model alignment. Contributed to open-source LLM projects with 2k+ GitHub stars.",
        "availability": "1 month",
        "location": "Boston, USA",
        "education": "PhD Natural Language Processing, CMU",
        "avatar": "MA",
        "linkedin": "linkedin.com/in/mohammed-alrashid",
    },
    {
        "id": 6,
        "name": "Neha Patel",
        "title": "Data Scientist",
        "years_experience": 3,
        "skills": ["Python", "scikit-learn", "NLP", "SQL", "Tableau", "pandas", "numpy"],
        "domain": "Data Science",
        "bio": "Builds ML models for e-commerce personalization and churn prediction. Reduced customer churn by 18% using NLP-powered sentiment analysis pipelines.",
        "availability": "immediate",
        "location": "Pune, India",
        "education": "M.Sc Data Science, BITS Pilani",
        "avatar": "NP",
        "linkedin": "linkedin.com/in/neha-patel-ds",
    },
    {
        "id": 7,
        "name": "James Wright",
        "title": "Backend Engineer",
        "years_experience": 5,
        "skills": ["Go", "Kubernetes", "gRPC", "PostgreSQL", "Redis", "Docker", "Python"],
        "domain": "Backend",
        "bio": "Infrastructure expert specializing in high-throughput microservices. Built payment processing APIs handling $500M/year transactions at a fintech company.",
        "availability": "2 months",
        "location": "London, UK",
        "education": "BSc Computer Science, Cambridge",
        "avatar": "JW",
        "linkedin": "linkedin.com/in/james-wright-backend",
    },
    {
        "id": 8,
        "name": "Aisha Johnson",
        "title": "Senior Data Engineer",
        "years_experience": 6,
        "skills": ["Spark", "Python", "Kafka", "Airflow", "dbt", "Snowflake", "BigQuery"],
        "domain": "Data Engineering",
        "bio": "Designed petabyte-scale data pipelines for a Fortune 500 company. Reduced data latency from 6 hours to 10 minutes using streaming architectures.",
        "availability": "1 month",
        "location": "New York, USA",
        "education": "MS Data Engineering, Columbia",
        "avatar": "AJ",
        "linkedin": "linkedin.com/in/aisha-johnson-data",
    },
    {
        "id": 9,
        "name": "Carlos Rivera",
        "title": "ML Engineer",
        "years_experience": 4,
        "skills": ["Python", "PyTorch", "Computer Vision", "ONNX", "FastAPI", "TensorRT", "Docker"],
        "domain": "Computer Vision",
        "bio": "Specializes in production-grade computer vision and model optimization. Deployed real-time object detection on edge devices with 3x throughput improvement.",
        "availability": "immediate",
        "location": "Mexico City, Mexico",
        "education": "BS Computer Science, UNAM",
        "avatar": "CR",
        "linkedin": "linkedin.com/in/carlos-rivera-cv",
    },
    {
        "id": 10,
        "name": "Divya Menon",
        "title": "Applied Scientist",
        "years_experience": 5,
        "skills": ["Python", "NLP", "Hugging Face", "AWS", "SageMaker", "PyTorch", "model deployment"],
        "domain": "Applied AI",
        "bio": "Applied scientist deploying NLP solutions on AWS SageMaker for enterprise clients. Reduced inference latency by 60% using quantization and distillation.",
        "availability": "1 month",
        "location": "Chennai, India",
        "education": "M.Tech AI, IIT Madras",
        "avatar": "DM",
        "linkedin": "linkedin.com/in/divya-menon-ai",
    },
    {
        "id": 11,
        "name": "Tom Fischer",
        "title": "Platform Engineer",
        "years_experience": 7,
        "skills": ["Kubernetes", "Terraform", "Python", "Prometheus", "Helm", "AWS", "GitOps"],
        "domain": "Platform",
        "bio": "Architected multi-cloud Kubernetes platforms for 10k+ node clusters at a cloud provider. Expert in GitOps, FinOps, and platform reliability engineering.",
        "availability": "3 months",
        "location": "Berlin, Germany",
        "education": "MSc Software Engineering, TU Munich",
        "avatar": "TF",
        "linkedin": "linkedin.com/in/tom-fischer-platform",
    },
    {
        "id": 12,
        "name": "Preethi Rajan",
        "title": "NLP Research Engineer",
        "years_experience": 4,
        "skills": ["Python", "PyTorch", "NLP", "BERT", "multilingual NLP", "information extraction", "LLM fine-tuning"],
        "domain": "NLP",
        "bio": "Specialized in low-resource language models and cross-lingual transfer learning. Built multilingual NER systems for 15+ Indian languages.",
        "availability": "immediate",
        "location": "Coimbatore, India",
        "education": "PhD Computational Linguistics, IISc",
        "avatar": "PR",
        "linkedin": "linkedin.com/in/preethi-rajan-nlp",
    },
    {
        "id": 13,
        "name": "David Park",
        "title": "Senior ML Engineer",
        "years_experience": 9,
        "skills": ["Python", "TensorFlow", "model deployment", "A/B testing", "SageMaker", "MLOps", "Spark"],
        "domain": "AI/ML",
        "bio": "Veteran ML engineer with deep expertise in recommendation systems serving 100M+ users. Previously at Netflix and Spotify scaling personalization models.",
        "availability": "1 month",
        "location": "Toronto, Canada",
        "education": "MS Machine Learning, University of Toronto",
        "avatar": "DP",
        "linkedin": "linkedin.com/in/david-park-ml",
    },
    {
        "id": 14,
        "name": "Yuki Tanaka",
        "title": "Robotics ML Engineer",
        "years_experience": 5,
        "skills": ["Python", "PyTorch", "Reinforcement Learning", "ROS", "C++", "CUDA", "OpenCV"],
        "domain": "Robotics",
        "bio": "Applies deep RL to robotic manipulation tasks at a leading robotics company. Strong background in sim-to-real transfer and real-time inference optimization.",
        "availability": "2 months",
        "location": "Tokyo, Japan",
        "education": "M.Eng Robotics, Kyoto University",
        "avatar": "YT",
        "linkedin": "linkedin.com/in/yuki-tanaka-robotics",
    },
    {
        "id": 15,
        "name": "Meera Krishnan",
        "title": "Generative AI Lead",
        "years_experience": 6,
        "skills": ["Python", "LLM fine-tuning", "Hugging Face", "LangChain", "RLHF", "PyTorch", "NLP"],
        "domain": "Generative AI",
        "bio": "Led generative AI product team building enterprise copilots for legal and finance domains. Pioneered RAG architectures for confidential document Q&A at scale.",
        "availability": "immediate",
        "location": "Bangalore, India",
        "education": "MS AI, IISc Bangalore",
        "avatar": "MK",
        "linkedin": "linkedin.com/in/meera-krishnan-genai",
    },
    {
        "id": 16,
        "name": "Omar Khalid",
        "title": "ML Infrastructure Engineer",
        "years_experience": 5,
        "skills": ["MLOps", "Python", "Kubernetes", "PyTorch", "model serving", "Triton", "Ray"],
        "domain": "ML Infrastructure",
        "bio": "Built scalable ML inference infrastructure serving 100M+ requests/day at a tech giant. Expert in Triton Inference Server, Ray Serve, and GPU cluster management.",
        "availability": "1 month",
        "location": "Dubai, UAE",
        "education": "BS Computer Engineering, AUC",
        "avatar": "OK",
        "linkedin": "linkedin.com/in/omar-khalid-mlinfra",
    },
    {
        "id": 17,
        "name": "Shreya Bose",
        "title": "Computer Vision Scientist",
        "years_experience": 4,
        "skills": ["Python", "PyTorch", "Computer Vision", "CLIP", "diffusion models", "ViT", "OpenCV"],
        "domain": "Computer Vision",
        "bio": "Works on multimodal vision-language models for medical imaging and diagnostics. Published 3 papers on zero-shot medical image segmentation.",
        "availability": "3 months",
        "location": "Kolkata, India",
        "education": "M.Tech Computer Vision, IIT Kharagpur",
        "avatar": "SB",
        "linkedin": "linkedin.com/in/shreya-bose-cv",
    },
    {
        "id": 18,
        "name": "Ethan Brooks",
        "title": "ML Engineer",
        "years_experience": 3,
        "skills": ["Python", "PyTorch", "NLP", "FastAPI", "Docker", "model deployment", "Redis"],
        "domain": "AI/ML",
        "bio": "Full-stack ML engineer building production APIs around NLP models. Deployed 5+ models to production serving real-time inference with sub-50ms latency.",
        "availability": "immediate",
        "location": "Austin, USA",
        "education": "BS Computer Science, UT Austin",
        "avatar": "EB",
        "linkedin": "linkedin.com/in/ethan-brooks-ml",
    },
    {
        "id": 19,
        "name": "Lakshmi Nair",
        "title": "Senior NLP Engineer",
        "years_experience": 7,
        "skills": ["Python", "NLP", "spaCy", "PyTorch", "information extraction", "BERT", "LLM fine-tuning"],
        "domain": "NLP",
        "bio": "Expert in information extraction and conversational AI systems for banking and insurance. Built knowledge graph pipelines processing 2M+ documents daily.",
        "availability": "1 month",
        "location": "Kochi, India",
        "education": "M.Tech NLP, IIT Delhi",
        "avatar": "LN",
        "linkedin": "linkedin.com/in/lakshmi-nair-nlp",
    },
    {
        "id": 20,
        "name": "Felix Wagner",
        "title": "Research Scientist",
        "years_experience": 5,
        "skills": ["Python", "PyTorch", "NLP", "model compression", "quantization", "Hugging Face", "ONNX"],
        "domain": "AI Research",
        "bio": "Focuses on efficient NLP — model pruning, quantization, and knowledge distillation. Reduced BERT inference cost by 70% while retaining 95% accuracy.",
        "availability": "immediate",
        "location": "Zurich, Switzerland",
        "education": "PhD Machine Learning, ETH Zurich",
        "avatar": "FW",
        "linkedin": "linkedin.com/in/felix-wagner-research",
    },
    {
        "id": 21,
        "name": "Ananya Gupta",
        "title": "Data Science Lead",
        "years_experience": 6,
        "skills": ["Python", "NLP", "PyTorch", "SQL", "Tableau", "A/B testing", "Spark"],
        "domain": "Data Science",
        "bio": "Led a 10-person data science team at a fintech unicorn. Drove $5M revenue impact through ML-powered credit scoring and fraud detection.",
        "availability": "2 months",
        "location": "Mumbai, India",
        "education": "M.Sc Statistics, ISI Kolkata",
        "avatar": "AG",
        "linkedin": "linkedin.com/in/ananya-gupta-ds",
    },
    {
        "id": 22,
        "name": "Ryan O'Brien",
        "title": "Frontend Engineer",
        "years_experience": 4,
        "skills": ["React", "TypeScript", "Next.js", "TailwindCSS", "GraphQL", "Framer Motion", "Node.js"],
        "domain": "Frontend",
        "bio": "Senior frontend engineer building high-performance web applications. Created component libraries used by 50+ teams and shipped products to 5M+ users.",
        "availability": "immediate",
        "location": "Dublin, Ireland",
        "education": "BS Computer Science, Trinity College Dublin",
        "avatar": "RO",
        "linkedin": "linkedin.com/in/ryan-obrien-frontend",
    },
]
